name: "Site"
description: "My Site"

url: "http://localhost:4000"
#baseurl: "https://realquestions.net.au/fbapp"
# paginate: 10
# gems: [jekyll-paginate]
# paginate_path: "page:num"

markdown: kramdown
permalink: pretty
highlighter: pygments.rb
